### ISSUE TITLE
Pod install fails

### ISSUE THREAD

**Issue by ozzy1873** [ko2ic/flutter_google_ad_manager#11]
Error message:
'flutter_google_ad_manager' does not specify a Swift version and none of the targets ('Runner') integrating it have the 'SWIFT_VERSION' attribute in at least one of the targets that integrate this pod.

**Comment by ko2ic** [comment]
@ozzy1873 It is troubleshooting of another plugin, but please refer to the following.

https://github.com/ko2ic/image_downloader/wiki#your-appdelegate-is-the-case-of-objective-c

**Comment by ozzy1873** [comment]
That worked. Thank you!
