### ISSUE TITLE
Android app crashes on startup

### ISSUE THREAD

**Issue by matte5031** [ko2ic/flutter_google_ad_manager#17]
Hello!

As soon as I add this plugin and try to run the app with both debug and release mode (tried in real device and simulator) it just crashes instantly. I've added this to the AndroidManifestaswell:

            <meta-data
                android:name="com.google.android.gms.ads.AD_MANAGER_APP"
                android:value="true"/>

Flutter version = 1.6.3 (currently latest beta version)
Dart version = 2.3.2

Any help or input appreciated, thanks!

**Comment by ko2ic** [comment]
I tried the example in the following environment, but there was no problem.
Please try it on the example.
I think there is a problem with your app rather than this plugin.  

```
Flutter 1.6.3 • channel beta • git@github.com:flutter/flutter.git
Framework • revision bc7bc94083 (2 weeks ago) • 2019-05-23 10:29:07 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)
```

**Comment by ShashankSirmour** [comment]
really app is crashing on startup I try to rebuild the app with and without plugin and all time it runs very fine with other packages 
  cupertino_icons: ^0.1.2
  html: ^0.13.3+3
  http: ^0.12.0
  bubble_bottom_bar: ^1.2.0
  cached_network_image: ^0.8.0
  auto_size_text: ^2.0.0+2
  flutter_widget_from_html_core:
  path_provider: 
  flutter_downloader: ^1.1.7
  scoped_model: ^1.0.1
  flutter_pdfview: ^1.0.0+4
  flutter_slidable: ^0.5.3
  share: ^0.6.1+1
  flutter_fluid_slider: ^1.0.1

but when I add this plugin I crash in a startup without any error. 

I set start splash screen to full screen I don't think it is the problem  as run fine with other plugins

**Comment by ko2ic** [comment]
@ShashankSirmour 

Is it working in the example?
in addition, please paste the error log and also check the following.

https://github.com/ko2ic/flutter_google_ad_manager/wiki

**Comment by ShashankSirmour** [comment]
my fault sorry I misplaced metadata  
 <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true"/>
