### ISSUE TITLE
ERROR CODE MEAN

### ISSUE THREAD

**Issue by ShashankSirmour** [ko2ic/flutter_google_ad_manager#20]
please guide what the different error code means

**Comment by ShashankSirmour** [comment]
why no need to add     " app Id"  anywhere

**Comment by ko2ic** [comment]
@ShashankSirmour 

Please refer to the following for app Id.

https://github.com/ko2ic/flutter_google_ad_manager/issues/8

**Comment by ShashankSirmour** [comment]
@ko2ic 
I can use AdMob banner id with this plugin?

**Comment by ko2ic** [comment]
@ShashankSirmour
You can not use.
This is a Google Ad Manager Plugin.
https://admanager.google.com/intl/en/home/
