### ISSUE TITLE
Update plugin to support Flutter v1.8.0

### ISSUE THREAD

**Issue by theneshofficial** [ko2ic/flutter_google_ad_manager#23]
I tried running on dev channel of flutter with v1.8.0, certainly it fixes the low performance issue but on plugin side the ads are not displaying the images. It just not showing any image, it's blank but onClick is working. Please update the plugin to support flutter v1.8.0. Thanks.

**Comment by ko2ic** [comment]
@theneshofficial 
Thank you for letting me know.
What is the error code coming back from?

**Comment by theneshofficial** [comment]
Hi @ko2ic Below is the output I get when run with flutter 1.8.0. It doesn't render any image view but onClick advertisement is working. The ad image is not showing. It also didn't throw any exception.

![ezgif-4-b0197196bbfb](https://user-images.githubusercontent.com/45613977/60648604-d21bac00-9e72-11e9-9205-62e6c057984d.gif)

**Comment by theneshofficial** [comment]
Hi @ko2ic, eventually Flutter 1.7.8+hotfix.3 has fixed this issue. So I'm closing it.

**Comment by ko2ic** [comment]
@theneshofficial 
I'm glad.
