### ISSUE TITLE
Smart_banner

### ISSUE THREAD

**Issue by cschellhas** [ko2ic/flutter_google_ad_manager#25]
Hi,

I dont know if it's realy a bug. But I cant use SMART_BANNER. If I change Banner Size in ADManager & Code to Smart Banner i only get ErrorCode:3. After changing back to MEDIUM_RECTANGLE everything works as expected.

Can someone prove that Smart Banners work?

**Comment by ko2ic** [comment]
@cschellhas For Android,  ```ErrorCode:3``` is ```ERROR_CODE_NO_FILL```. Perhaps the request is successful.

https://developers.google.com/android/reference/com/google/android/gms/ads/doubleclick/PublisherAdRequest.html?hl=ja#ERROR_CODE_NO_FILL

For iOS, the example is successful.

However, I've never used SMART_BANNER in a production environment, so I can't confirm that it's really working properly.

**Comment by GeertJohan** [comment]
I also get errorCode: 3 with smart_banner. In my case this means that there is no available ad to display. It probably depends on the ad network that you use if there are ads available for it.
