### ISSUE TITLE
Compile issue for iOS

### ISSUE THREAD

**Issue by ashbressler** [ko2ic/flutter_google_ad_manager#3]
I'm getting the following error when trying to compile the plugin for iOS:

    /Users/xxxxxxx/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_google_ad_manager-0.6.2/ios/Classes/InterstitialAd.swift:84:55: error: value of optional type 'String?' must be unwrapped to a value of type 'String'
            interstitialAd = DFPInterstitial(adUnitID: ad.adUnitID)

I'm on XCode Version 10.2 (10E125) and have the command line tools installed. I have version 0.6.2 of this plugin installed.

**Comment by ashbressler** [comment]
I fixed the issue and one other that I was having with test devices and created a pull request https://github.com/ko2ic/flutter_google_ad_manager/pull/4

**Comment by ko2ic** [comment]
Resolved in #4.
