### ISSUE TITLE
Allow for re-loading the banner ads

### ISSUE THREAD

**Issue by ashbressler** [ko2ic/flutter_google_ad_manager#5]
I would like to be able to call the controller.load from my app to re-load the banner ads based on a user interaction. I believe this could work by passing the _DFPBannerViewController back to the DFPBanner widget and not keeping it private, I've seen this with other Widgets (webview_flutter as an example).

I can try to make a PR for this.

**Comment by ko2ic** [comment]
@ashbressler Than you for your PullRequest.

**Comment by ko2ic** [comment]
@ashbressler Thank you for your contribution!     
I was able to confirm that it works.

I will make a few changes and release.

**Comment by ko2ic** [comment]
@ashbressler v0.7.0 has been released.
Please try using it and let me know if there is a problem.
Thanks!!
