### ISSUE TITLE
iOS Build failing

### ISSUE THREAD

**Issue by AdbayGit** [ko2ic/flutter_google_ad_manager#7]
I get the app to build with ads just fine for Android, but iOS keeps failing in various ways. This is the current error I'm getting:

Error: definition of 'FlutterGoogleAdManagerPlugin' must be imported from module 'flutter_google_ad_manager.FlutterGoogleAdManagerPlugin' before it is required
    @implementation FlutterGoogleAdManagerPlugin

Thrown from: .pub-cache/hosted/pub.dartlang.org/flutter_google_ad_manager-0.6.3+2/ios/Classes/FlutterGoogleAdManagerPlugin.m:4:17:

I added to my Info.plist:

	<key>io.flutter.embedded_views_preview</key>
	<true/>
	<key>GADIsAdManagerApp</key>
	<true/>

I don't have a lot of experience with iOS so this one is throwing me for a loop.

**Comment by ko2ic** [comment]
@AdbayGit
Please refer to the following

https://github.com/ko2ic/image_downloader/wiki#your-appdelegate-is-the-case-of-objective-c

**Comment by ko2ic** [comment]
@AdbayGit If the cause is different, please try v0.7.0.

**Comment by AdbayGit** [comment]
Thank you for the help. This solved my issue.
