### ISSUE TITLE
App ID?

### ISSUE THREAD

**Issue by ozzy1873** [ko2ic/flutter_google_ad_manager#8]
I'm not seeing where we set our appid.

**Comment by ko2ic** [comment]
@ozzy1873

This seems like a question unrelated to this plugin.  Are there any issues specific to this plugin?

**Comment by ko2ic** [comment]
@ozzy1873

There should be no appid settings in google ad mamager.  This plugin is not admob.
Please let me know if I'm wrong.

**Comment by ozzy1873** [comment]
I am coming from admob. I see that this no longer seems to be required. Thanks!

**Comment by ozzy1873** [comment]
Actually, it is still required on iOS. I had to add <key>GADApplicationIdentifier</key> to the info.plist file.

**Comment by ko2ic** [comment]
@ozzy1873 It is also admob.
In the case of A, the following settings are required.

```
<key>GADIsAdManagerApp</key>
<true/>
```
