### ISSUE TITLE
Test Devices

### ISSUE THREAD

**Issue by ozzy1873** [ko2ic/flutter_google_ad_manager#9]
I'm thinking that test ads should be shown on test devices regardless of whether 'isDevelop' is true or false. That way I can run a release build on my test device with isDevelop==false and still safely show test ads.

**Comment by ko2ic** [comment]
@ozzy1873

Set it to true if you want to test, and set it to false in production.  I think it is a very easy to understand and simple specification.

**Comment by ko2ic** [comment]
Maybe there is a problem with naming.  For example,if named isTestAd, you will set it without misunderstanding.

**Comment by ozzy1873** [comment]
I understand, but that is not the problem. Consider this use case: I have an app deployed in the app store and that app has isDevelop set to false (of course). Now I want to install that app from the app store onto my test device. In this case, I still want my device to display test ads.

**Comment by ko2ic** [comment]
@ozzy1873 Both the Admob SDK and the Google Ad Manager SDK need to have an ad unit ID for testing in order to display Test ads.
I think that changing the value of ```isDevelop```  and changing the ad unit id is the same thing.

Regardless of this plugin, it is a specification of the Native SDK.
The same problem will occur even if implemented with native SDK.

If you want to switch the settings of the app downloaded from the app store, it is recommended to control with Firebase Remote Config.

**Comment by ozzy1873** [comment]
There is a difference between using test unit IDs and adding your device as a test device.
With test units - you see the simple test ad. You also need to refactor your code before release. 
With test devices - you see actual ads from your unit, but they're in "test mode"

**Comment by ko2ic** [comment]
@ozzy1873 
Do you think that if you just register a test device, test ads will be displayed without specifying a test unit id?

My understanding of google ad manager SDK is as follows.

* If do not specify a unit id for test ads, the test ads will not be displayed.
* If a test device is not registered, a test advertisement will not be displayed on the actual device even if a test unit id is specified.

**Comment by ozzy1873** [comment]
My understanding is that if you register a test device, test ads will always be displayed on that device, even without specifying a test unit ID. Perhaps you can run an experiment to know for sure?

**Comment by ko2ic** [comment]
@ozzy1873 I experimented. You are right.
I will fix to display a test ad if ```TestDevices``` is implemented.

**Comment by ko2ic** [comment]
@ozzy1873 v0.8.0 has been released. Please try using it.
Thank you very much for your advice!!

**Comment by ozzy1873** [comment]
This is working now when compiled for debugging; however, when compiled for release, the test ads are not being served when the app is running on a test device. When running on a test device, test ads should always be served in both debug and release modes. I am assuming the ads being served are not test ads because they are not labeled with "Test Ad".

I reviewed your code, but I don't see why this is happening. Perhaps you have an idea?

Edit:
Mediated ads do NOT render a Test Ad label. 
See [https://developers.google.com/admob/android/test-ads](url)

You can ignore this comment. I would have deleted it, but I thought it might be useful to others.
